'use strict'

const Fault = require('cortex-service/lib/fault');

[
  ['cortex.accepted.mediaNotReady', 'kMediaNotReady', 'files', 202, 'The resource has been created but is not ready for streaming.'],
  ['cortex.accessDenied.accountActivationRequired', 'kAccountActivationRequired', 'registration', 403, 'Account must be activated to login.'],
  ['cortex.accessDenied.accountLocked', 'kAccountLocked', 'auth', 403, 'Account access has been disabled.'],
  ['cortex.accessDenied.accountNotActivated', 'kAccountNotActivated', 'account', 403, 'Account is not yet activated.'],
  ['cortex.accessDenied.app', 'kAccessDenied', 'apps', 403, 'App client access denied.'],
  ['cortex.accessDenied.appDisabled', 'kAccessDenied', 'apps', 403, 'App disabled.'],
  ['cortex.accessDenied.appReadOnly', 'kAccessDenied', 'apps', 403, 'App is read only.'],
  ['cortex.accessDenied.appSuspended', 'kAccessDenied', 'apps', 403, 'App suspended.'],
  ['cortex.accessDenied.autoConnectionRequiresAccess', 'kAccessDenied', 'account', 403, 'An automatic connection cannot be made unless the caller has the required access level to the connection target.'],
  ['cortex.accessDenied.badPassword', 'kInvalidCredentials', 'auth', 403, 'Invalid password.'],
  ['cortex.accessDenied.connection', 'kAccessDenied', 'connections', 403, 'Connection access denied.'],
  ['cortex.accessDenied.connectionRequiresVerification', 'kAccountNotVerified', 'account', 403, 'Account must be verified before connections can be made.'],
  ['cortex.accessDenied.connectionsDisabled', 'kAccessDenied', 'connections', 403, 'Connections are disabled for object.'],
  ['cortex.accessDenied.csrfTokenMismatch', 'kCSRFTokenMismatch', 'sessions', 403, 'CSRF token mismatch.'],
  ['cortex.accessDenied.deploymentEnv', 'kAccessDenied', 'deployment', 403, 'This organization environment is not configured for deployments.'],
  ['cortex.accessDenied.deploymentInProgress', 'kDeployment', 'deployment', 403, 'A deployment is in progress.'],
  ['cortex.accessDenied.deploymentTarget', 'kAccessDenied', 'deployment', 403, 'Invalid deployment target.'],
  ['cortex.accessDenied.duplicatePassword', 'kDuplicate', 'account', 403, 'Your new password must be different than the old one.'],
  ['cortex.accessDenied.feature', 'kAccessDenied', 'api', 403, 'Feature not available.'],
  ['cortex.accessDenied.inUse', 'kAccessDenied', 'fault', 403, 'The resource is in use and cannot be removed.'],
  ['cortex.accessDenied.inaccessibleProperty', 'kAccessDenied', 'db', 403, 'Cannot perform operation on non-accessible property.'],
  ['cortex.accessDenied.instanceCreate', 'kAccessDenied', 'db', 403, 'Create access denied.'],
  ['cortex.accessDenied.instanceDelete', 'kAccessDenied', 'db', 403, 'Delete access denied.'],
  ['cortex.accessDenied.instanceRead', 'kAccessDenied', 'db', 403, 'Read access denied.'],
  ['cortex.accessDenied.instanceUpdate', 'kAccessDenied', 'db', 403, 'Update access denied.'],
  ['cortex.accessDenied.invalidCredentials', 'kInvalidCredentials', 'auth', 403, 'Invalid email/password combination.'],
  ['cortex.accessDenied.invalidDeploymentCredentials', 'kInvalidArgument', 'deployment', 403, 'Invalid deployment credentials.'],
  ['cortex.accessDenied.invalidJwt', 'kInvalidCredentials', 'jwt', 403, 'Invalid access token.'],
  ['cortex.accessDenied.invalidJwtApp', 'kInvalidCredentials', 'jwt', 403, 'Invalid access token app.'],
  ['cortex.accessDenied.invalidRequestSignature', 'kInvalidRequestSignature', 'auth', 403, 'Invalid request signature.'],
  ['cortex.accessDenied.locationAccessRevoked', 'kLocationAccessRevoked', 'location', 403, 'Access from this location has been revoked.'],
  ['cortex.accessDenied.locationClientMismatch', 'kLocationClientMismatch', 'location', 403, 'Location/Access client mismatch.'],
  ['cortex.accessDenied.loggedInElsewhere', 'kLoggedInElsewhere', 'sessions', 403, 'Logged in elsewhere.'],
  ['cortex.accessDenied.invalidLoginMethod', 'kInvalidLoginMethod', 'auth', 403, 'Invalid login method.'],
  ['cortex.accessDenied.maintenance', 'kMaintenance', 'env', 403, 'The API is currently undergoing maintenance.'],
  ['cortex.accessDenied.maxAccounts', 'kMaxAllowed', 'accounts', 403, 'The user account quota has been exceeded.'],
  ['cortex.accessDenied.maxJobsPerDay', 'kMaxAllowed', 'jobs', 403, 'Max jobs per day quota exceeded.'],
  ['cortex.accessDenied.maxJwtPerSubject', 'kAccessDenied', 'jwt', 403, 'Maximum number of tokens reached for this subject.'],
  ['cortex.accessDenied.maxRooms', 'kAccessDenied', 'fault', 403, 'Max concurrent rooms.'],
  ['cortex.accessDenied.noCredentialsSupplied', 'kNoCredentialsSupplied', 'auth', 403, 'No access credentials were supplied.'],
  ['cortex.accessDenied.notDeletable', 'kNotDeletable', 'error', 403, 'Resource cannot be deleted.'],
  ['cortex.accessDenied.notLoggedIn', 'kNotLoggedIn', 'sessions', 403, 'You must be logged in to access this resource.'],
  ['cortex.accessDenied.notPullable', 'kNotPullable', 'error', 403, 'Removal from collection not supported.'],
  ['cortex.accessDenied.notWritable', 'kNotWritable', 'error', 403, 'Resource/Property is not writable.'],
  ['cortex.accessDenied.passwordExpired', 'kPasswordExpired', 'auth', 403, 'Your password has expired.'],
  ['cortex.accessDenied.policy', 'kAccessDenied', 'auth', 403, 'Access denied by policy.'],
  ['cortex.accessDenied.principal', 'kAccessDenied', 'auth', 403, 'Access denied to principal.'],
  ['cortex.accessDenied.privateFacet', 'kAccessDenied', 'media', 403, 'Access to private facet is only allowed by the creator.'],
  ['cortex.accessDenied.propertyDelete', 'kAccessDenied', 'db', 403, 'Property delete access denied.'],
  ['cortex.accessDenied.propertyPull', 'kAccessDenied', 'db', 403, 'Property pull access denied.'],
  ['cortex.accessDenied.propertyRead', 'kAccessDenied', 'fault', 403, 'Property read access denied.'],
  ['cortex.accessDenied.propertyUpdate', 'kAccessDenied', 'db', 403, 'Property update access denied.'],
  ['cortex.accessDenied.providerRegistrationDisabled', 'kProviderRegistrationDisabled', 'account', 403, 'Provider registration is not enabled.'],
  ['cortex.accessDenied.referencedContext', 'kAccessDenied', 'db', 403, 'Insufficient access to referenced context.'],
  ['cortex.accessDenied.registrationInvitationRequired', 'kRegistrationInvitationRequired', 'registration', 403, 'Registration requires a valid invitation.'],
  ['cortex.accessDenied.role', 'kAccessDenied', 'apps', 403, 'Insufficient role access.'],
  ['cortex.accessDenied.room', 'kAccessDenied', 'fault', 403, 'Banned from room.'],
  ['cortex.accessDenied.roomsDisabled', 'kAccessDenied', 'fault', 403, 'Rooms disabled.'],
  ['cortex.accessDenied.route', 'kAccessDenied', 'fault', 403, 'Route access denied.'],
  ['cortex.accessDenied.scope', 'kAccessDenied', 'support', 403, 'Missing a required JWT auth scope.'],
  ['cortex.accessDenied.scoped', 'kAccessDenied', 'support', 403, 'Call by JWT scoped principal not permitted.'],
  ['cortex.accessDenied.scriptsDisabled', 'kAccessDenied', 'scripts', 403, 'Scripts are disabled in this environment.'],
  ['cortex.accessDenied.selfRegistrationDisabled', 'kSelfRegistrationDisabled', 'account', 403, 'Self registration is not enabled.'],
  ['cortex.accessDenied.sessionExpired', 'kSessionExpired', 'sessions', 403, 'Your session has expired.'],
  ['cortex.accessDenied.sessionOrgMismatch', 'kSessionOrgMismatch', 'sessions', 403, 'The application and session Orgs do not match.'],
  ['cortex.accessDenied.shareAccess', 'kAccessDenied', 'fault', 403, 'Share access is required.'],
  ['cortex.accessDenied.supportDisabled', 'kAccessDenied', 'support', 403, 'Support login is disabled.'],
  ['cortex.accessDenied.supportPinned', 'kAccessDenied', 'support', 403, 'Support login is pinned to another account.'],
  ['cortex.accessDenied.supportReasonRequired', 'kAccessDenied', 'support', 403, 'Support login requires a reason for the login.'],
  ['cortex.accessDenied.unspecified', 'kAccessDenied', 'error', 403, 'Access denied.'],
  ['cortex.accessDenied.unverifiedLocation', 'kUnverifiedLocation', 'location', 403, 'Access by this location is pending account holder verification.'],
  ['cortex.accessDenied.view', 'kAccessDenied', 'db', 403, 'View access denied.'],
  ['cortex.accessDenied.writeOnce', 'kWriteOnce', 'error', 403, 'Property cannot be overwritten.'],
  ['cortex.conflict.accountAlreadyActivated', 'kExists', 'fault', 409, 'Account already activated.'],
  ['cortex.conflict.accountAlreadyVerified', 'kExists', 'fault', 409, 'Account already verified.'],
  ['cortex.conflict.activationAlreadySent', 'kActivationAlreadySent', 'admin', 409, 'An account activation email has already been sent to this address.'],
  ['cortex.conflict.connectionExists', 'kExists', 'connections', 409, 'Connection already exists.'],
  ['cortex.conflict.duplicateEmail', 'kExists', 'account', 409, 'An account with this email address already exists.'],
  ['cortex.conflict.duplicateUsername', 'kExists', 'account', 409, 'An account with this username already exists.'],
  ['cortex.conflict.duplicateKey', 'kDuplicateKey', 'db', 409, 'Duplicate value for unique index.'],
  ['cortex.conflict.exists', 'kExists', 'error', 409, 'Resource already exists.'],
  ['cortex.conflict.lockExists', 'kExists', 'error', 409, 'Lock exists.'],
  ['cortex.conflict.sequencing', 'kSequencingError', 'db', 409, 'Sequencing error. Device contention on a document could not be resolved.'],
  ['cortex.conflict.staleDocument', 'kStaleDocument', 'db', 409, 'Stale document.'],
  ['cortex.conflict.uniqueInArray', 'kDuplicateKey', 'db', 409, 'Duplicate value found in the collection.'],
  ['cortex.conflict.unspecified', 'kConflict', 'db', 409, 'Resource conflict.'],
  ['cortex.conflict.versionOutOfDate', 'kConflict', 'db', 409, 'The version is out of date.'],
  ['cortex.error.aborted', 'kCancelled', 'error', 500, 'Operation aborted.'],
  ['cortex.error.couldNotReadCookies', 'kCouldNotReadCookies', 'location', 500, 'Could not read cookies.'],
  ['cortex.error.db', 'kError', 'db', 500, 'A database error occured.'],
  ['cortex.error.deploymentRunMismatch', 'kError', 'deployment', 500, 'Deployment last-run identifier does not match.'],
  ['cortex.error.facet', 'kScriptError', 'files', 500, 'File facet has errors.'],
  ['cortex.error.listWriteThrough', 'kError', 'db', 500, 'List write-through had errors.'],
  ['cortex.error.messageQueueFailed', 'kMessageQueueFailed', 'queue', 500, 'Failed to queue message(s).'],
  ['cortex.error.netInvalidResponseStatus', 'kInvalidResponseStatus', 'client', 500, 'Result received with invalid http response code.'],
  ['cortex.error.netMissingResponse', 'kMissingResponse', 'client', 500, 'Missing response. Expected a fault or result.'],
  ['cortex.error.netMissingResult', 'kMissingResult', 'client', 500, 'Missing result.'],
  ['cortex.error.queueCantLockMessage', 'kQueueCantLockMessage', 'queue', 500, 'Could not lock for remove/update.'],
  ['cortex.error.queueProcessError', 'kQueueProcessError', 'queue', 500, 'Process error.'],
  ['cortex.error.queueTaskProcessor', 'kQueueTaskProcessor', 'queue', 500, 'Task had errors.'],
  ['cortex.error.renderTemplate', 'kError', 'notifications', 500, 'One or more template parts failed to render.'],
  ['cortex.error.sessionInitFailure', 'kError', 'sessions', 500, 'Session failed to initialize.'],
  ['cortex.error.sessionRequired', 'kSessionRequired', 'sessions', 500, 'A session is required.'],
  ['cortex.error.smsNotification', 'kSmsError', 'sms', 500, 'SMS Error.'],
  ['cortex.error.triggerCancelled', 'kError', 'scripts', 500, 'Operation was cancelled by trigger.'],
  ['cortex.error.unspecified', 'kError', 'error', 500, 'Error.'],
  ['cortex.error.virusDetected', 'kVirusFound', 'files', 500, 'A virus was detected.'],
  ['cortex.expired.app', 'kExpired', 'apps', 410, 'App key expired.'],
  ['cortex.expired.deployment', 'kExpired', 'deployment', 410, 'Expired deployment token.'],
  ['cortex.expired.jwt', 'kTokenExpired', 'jwt', 410, 'Expired access token.'],
  ['cortex.expired.locationToken', 'kExpired', 'locations', 410, 'Expired location verification token.'],
  ['cortex.expired.unspecified', 'kExpired', 'error', 410, 'Resource expired.'],
  ['cortex.invalidArgument.JSONSchema', 'kInvalidJSONSchema', 'validation', 400, 'Please enter a valid JSON schema.'],
  ['cortex.invalidArgument.JSONSchemaValidation', 'kInvalidArgument', 'validation', 400, 'JSON schema validation failed.'],
  ['cortex.invalidArgument.allowLevel', 'kInvalidArgument', 'validation', 400, 'Invalid acl allow level.'],
  ['cortex.invalidArgument.ambiguousDeploymentMapping', 'kInvalidArgument', 'deployment', 400, 'Ambiguous mapping must be forced.'],
  ['cortex.invalidArgument.authScope', 'kAuthScope', 'auth', 400, 'Invalid authentication scope.'],
  ['cortex.invalidArgument.autoConnectionRequiresId', 'kInvalidArgument', 'connections', 400, 'Automatic connections must target an account identifier.'],
  ['cortex.invalidArgument.autoCreateCircularReference', 'kInvalidArgument', 'db', 400, 'A circular reference exists in the autoCreate configuration.'],
  ['cortex.invalidArgument.badDbValue', 'kInvalidArgument', 'db', 400, 'Invalid query expression and/or value.'],
  ['cortex.invalidArgument.castError', 'kCastError', 'validation', 400, 'Cast error.'],
  ['cortex.invalidArgument.certificateOrKeyFormat', 'kInvalidFormat', 'validation', 400, 'The certificate/key format is invalid.'],
  ['cortex.invalidArgument.circularReference', 'kInvalidArgument', 'db', 400, 'Value contains a circular reference.'],
  ['cortex.invalidArgument.connectionTarget', 'kInvalidArgument', 'connections', 400, 'Invalid connection target.'],
  ['cortex.invalidArgument.connectionToken', 'kInvalidArgument', 'connections', 400, 'Invalid connection token.'],
  ['cortex.invalidArgument.creatableOnly', 'kCreatableOnly', 'validation', 400, 'Property is only writable on creation.'],
  ['cortex.invalidArgument.creationDisabled', 'kInvalidArgument', 'db', 400, 'Instance creation is currently disabled.'],
  ['cortex.invalidArgument.cursorOrArrayExpected', 'kInvalidArgument', 'db', 400, 'Expecting a cursor or array.'],
  ['cortex.invalidArgument.customName', 'kInvalidArgument', 'validation', 400, 'Invalid custom/namespaced value.'],
  ['cortex.invalidArgument.date', 'kInvalidArgument', 'validation', 400, 'Invalid date.'],
  ['cortex.invalidArgument.dateOfBirth', 'kInvalidDateOfBirth', 'validation', 400, 'Invalid date of birth.'],
  ['cortex.invalidArgument.deletionDisabled', 'kInvalidArgument', 'db', 400, 'Instance deletion is currently disabled.'],
  ['cortex.invalidArgument.dollarPrefixedDbKey', 'kInvalidArgument', 'db', 400, 'Dollar ($) prefixed fields are not valid for storage.'],
  ['cortex.invalidArgument.dottedDbFieldName', 'kInvalidArgument', 'db', 400, 'Dotted field names are not valid for storage.'],
  ['cortex.invalidArgument.emailAddress', 'kInvalidEmailAddress', 'validation', 400, 'Invalid email address.'],
  ['cortex.invalidArgument.emailFormat', 'kInvalidEmailFormat', 'validation', 400, 'Invalid email address format.'],
  ['cortex.invalidArgument.username', 'kInvalidUsername', 'validation', 400, 'Invalid username format.'],
  ['cortex.invalidArgument.emptyOperationsPayload', 'kInvalidArgument', 'patch', 400, 'Empty operations payload. Nothing to do.'],
  ['cortex.invalidArgument.enumValue', 'kEnumValue', 'validation', 400, 'Please enter a value from the list.'],
  ['cortex.invalidArgument.envDisabled', 'kOrgDisabled', 'env', 400, 'Org is not active.'],
  ['cortex.invalidArgument.fingerprintMismatch', 'kFingerprintMismatch', 'location', 400, 'Fingerprint does not match session.'],
  ['cortex.invalidArgument.iPv4AddrOrCidr', 'kInvalidIPv4AddrOrCidr', 'validation', 400, 'Enter a valid IPv4 address or IPv4 CIDR range.'],
  ['cortex.invalidArgument.illegalExpansion', 'kIllegalExpansion', 'error', 400, 'This property cannot be expanded.'],
  ['cortex.invalidArgument.inactive', 'kInvalidArgument', 'error', 400, 'Resource is inactive.'],
  ['cortex.invalidArgument.inactiveDeploymentTarget', 'kInvalidArgument', 'deployment', 400, 'Deployment target is inactive.'],
  ['cortex.invalidArgument.instanceRetyping', 'kInvalidArgument', 'db', 400, 'Object instances cannot be re-typed.'],
  ['cortex.invalidArgument.instanceTypeMismatch', 'kInvalidArgument', 'db', 400, 'Invalid or mismatched object type.'],
  ['cortex.invalidArgument.invalidApiVersion', 'kInvalidApiVersion', 'error', 400, 'Invalid API Version.'],
  ['cortex.invalidArgument.invalidCoordinate', 'kInvalidCoordinate', 'validation', 400, 'Must be a valid 2 element coordinate array.'],
  ['cortex.invalidArgument.invalidDeploymentId', 'kInvalidArgument', 'deployment', 400, 'Invalid deployment identifier.'],
  ['cortex.invalidArgument.invalidJSON', 'kInvalidJSON', 'validation', 400, 'Please enter valid JSON.'],
  ['cortex.invalidArgument.invalidObjectId', 'kInvalidArgument', 'error', 400, 'Invalid object identifier.'],
  ['cortex.invalidArgument.invalidNumber', 'kInvalidNumber', 'validation', 400, 'Invalid number.'],
  ['cortex.invalidArgument.invalidString', 'kInvalidString', 'validation', 400, 'Invalid string.'],
  ['cortex.invalidArgument.locale', 'kInvalidArgument', 'validation', 400, 'Invalid locale'],
  ['cortex.invalidArgument.locationAlreadyVerified', 'kLocationAlreadyVerified', 'location', 400, 'Location already verified.'],
  ['cortex.invalidArgument.locationFingerprint', 'kInvalidFingerprint', 'location', 400, 'Invalid location fingerprint.'],
  ['cortex.invalidArgument.locationToken', 'kInvalidArgument', 'locations', 400, 'Invalid location verification token.'],
  ['cortex.invalidArgument.matchExpected', 'kInvalidArgument', 'db', 400, 'Expected a match document or identifier.'],
  ['cortex.invalidArgument.maxAllowed', 'kMaxAllowed', 'validation', 400, 'Too many items of this type in the collection.'],
  ['cortex.invalidArgument.maxInsertsPerCall', 'kInvalidArgument', 'db', 400, 'The maximum number of inserted documents per call has been reached.'],
  ['cortex.invalidArgument.maxItems', 'kMaxItems', 'validation', 400, 'Too many items in the collection/array.'],
  ['cortex.invalidArgument.maxLength', 'kInvalidArgument', 'validation', 400, 'Max length exceeded.'],
  ['cortex.invalidArgument.maxScriptLength', 'kInvalidArgument', 'validation', 400, 'Max script length exceeded.'],
  ['cortex.invalidArgument.minItems', 'kMinItems', 'validation', 400, 'Not enough items in the collection/array.'],
  ['cortex.invalidArgument.minRequired', 'kMinRequired', 'validation', 400, 'Not enough items of this type in the collection.'],
  ['cortex.invalidArgument.mismatchedContentType', 'kMismatchedMediaContentType', 'files', 400, 'Uploaded file content type must match the source.'],
  ['cortex.invalidArgument.missingEnvCode', 'kInvalidArgument', 'env', 400, 'Invalid or missing organization environment code.'],
  ['cortex.invalidArgument.missingNotificationPayload', 'kInvalidArgument', 'notifications', 400, 'Missing notification worker payload.'],
  ['cortex.invalidArgument.missingTemplateOrMessage', 'kInvalidArgument', 'notifications', 400, 'Missing notification worker payload template or message.'],
  ['cortex.invalidArgument.missingValidatorDefinition', 'kInvalidArgument', 'db', 400, 'This validator has no definition.'],
  ['cortex.invalidArgument.noConnectionApp', 'kInvalidArgument', 'connections', 400, 'Connections must be created within the context of an application.'],
  ['cortex.invalidArgument.noConnectionTargets', 'kInvalidArgument', 'connections', 400, 'No connection targets were specified.'],
  ['cortex.invalidArgument.notificationTemplateVariable', 'kInvalidArgument', 'notifications', 400, 'One or more template variables are missing from the notification worker payload.'],
  ['cortex.invalidArgument.npi', 'kInvalidNPI', 'validation', 400, 'Invalid NPI.'],
  ['cortex.invalidArgument.nullInstanceType', 'kInvalidArgument', 'db', 400, 'Object type cannot be written as null. It must equal one of the named types.'],
  ['cortex.invalidArgument.numberExpected', 'kNumberExpected', 'validation', 400, 'Number expected.'],
  ['cortex.invalidArgument.object', 'kInvalidObject', 'error', 400, 'Invalid or unknown object.'],
  ['cortex.invalidArgument.objectExpectedForPatchOperation', 'kInvalidArgument', 'patch', 400, 'Patch entry must be an object.'],
  ['cortex.invalidArgument.objectExpectedForPatchValue', 'kInvalidArgument', 'patch', 400, 'Patch operation value must be an object.'],
  ['cortex.invalidArgument.operationBulkDepthExceeded', 'kInvalidArgument', 'db', 400, 'Max bulk operation depth exceeded.'],
  ['cortex.invalidArgument.passwordStrength', 'kInvalidArgument', 'validation', 400, 'The chosen password does not meet the minimum password strength requirement.'],
  ['cortex.invalidArgument.pathAndValueExpectedForPullOperation', 'kInvalidArgument', 'patch', 400, 'Pull requires a path and value.'],
  ['cortex.invalidArgument.phoneNumberFormat', 'kInvalidPhoneNumberFormat', 'validation', 400, 'Invalid phone number format.'],
  ['cortex.invalidArgument.primitiveExpected', 'kInvalidArgument', 'db', 400, 'Primitive value expected.'],
  ['cortex.invalidArgument.primitiveExpectedforPatchRemoveValue', 'kInvalidArgument', 'patch', 400, 'Patch remove operation value must be a primitive.'],
  ['cortex.invalidArgument.query', 'kInvalidArgument', 'db', 400, 'Invalid query arguments.'],
  ['cortex.invalidArgument.requireConnectionAccept', 'kInvalidArgument', 'connections', 400, 'Connections cannot be auto-created for this object.'],
  ['cortex.invalidArgument.required', 'kRequired', 'validation', 400, 'Please enter a value.'],
  ['cortex.invalidArgument.script', 'kInvalidArgument', 'validation', 400, 'Invalid script.'],
  ['cortex.invalidArgument.scriptCompilation', 'kScriptCompilationError', 'validation', 400, 'Script compilation error.'],
  ['cortex.invalidArgument.stageJSONFormat', 'kInvalidArgument', 'parser', 400, 'Invalid JSON format.'],
  ['cortex.invalidArgument.stageObjectExpected', 'kInvalidArgument', 'parser', 400, 'Object expected for expression.'],
  ['cortex.invalidArgument.staleRequestSignature', 'kStaleRequestSignature', 'auth', 400, 'Stale request signature. Use the Medable-Server-Time response header to correct drift.'],
  ['cortex.invalidArgument.state', 'kInvalidArgument', 'error', 400, 'Invalid object state.'],
  ['cortex.invalidArgument.string', 'kInvalidArgument', 'validation', 400, 'Invalid string.'],
  ['cortex.invalidArgument.stringExpected', 'kInvalidArgument', 'validation', 400, 'String expected.'],
  ['cortex.invalidArgument.stringExpectedforPatchPath', 'kInvalidArgument', 'patch', 400, 'Patch operation path property must be a string.'],
  ['cortex.invalidArgument.timeZone', 'kInvalidArgument', 'validation', 400, 'Invalid timezone.'],
  ['cortex.invalidArgument.tooLarge', 'kRequestTooLarge', 'auth', 400, 'Value too large.'],
  ['cortex.invalidArgument.unspecified', 'kInvalidArgument', 'error', 400, 'Invalid Argument.'],
  ['cortex.invalidArgument.unsupportedBulkOperation', 'kInvalidArgument', 'db', 400, 'Unsupported bulk operation.'],
  ['cortex.invalidArgument.unsupportedContentEncoding', 'kInvalidArgument', 'error', 400, 'Unsupported content encoding.'],
  ['cortex.invalidArgument.updateDisabled', 'kInvalidArgument', 'db', 400, 'Instance update is currently disabled.'],
  ['cortex.invalidArgument.url', 'kInvalidArgument', 'validation', 400, 'Invalid URL.'],
  ['cortex.invalidArgument.validation', 'kValidationError', 'error', 400, 'Validation error.'],
  ['cortex.invalidArgument.valueExpectedForPatchValue', 'kInvalidArgument', 'patch', 400, 'Missing patch operation value property.'],
  ['cortex.invalidArgument.versionRequired', 'kRequired', 'validation', 428, 'Versioned object requires version to update.'],
  ['cortex.notFound.account', 'kNotFound', 'fault', 404, 'Account not found.'],
  ['cortex.notFound.accountToken', 'kNotFound', 'fault', 404, 'Invalid account token.'],
  ['cortex.notFound.app', 'kNotFound', 'apps', 404, 'App not found.'],
  ['cortex.notFound.appRsa', 'kNotFound', 'apps', 404, 'App does not have a valid RSA key pair.'],
  ['cortex.notFound.arrayValue', 'kNotFound', 'db', 404, 'Element not found in array.'],
  ['cortex.notFound.cacheKey', 'kNotFound', 'fault', 404, 'Cache key not found.'],
  ['cortex.notFound.cursor', 'kNotFound', 'db', 404, 'Cursor not found.'],
  ['cortex.notFound.deploymentTarget', 'kNotFound', 'deployment', 404, 'Deployment target was not found.'],
  ['cortex.notFound.document', 'kNotFound', 'db', 404, 'Document not found.'],
  ['cortex.notFound.env', 'kOrgControlInvalidOrg', 'env', 404, 'Unrecognized organization environment.'],
  ['cortex.notFound.expansionContext', 'kNotFound', 'db', 404, 'Expansion context not found.'],
  ['cortex.notFound.facet', 'kNotFound', 'files', 404, 'Facet not found.'],
  ['cortex.notFound.file', 'kNotFound', 'files', 404, 'File not found.'],
  ['cortex.notFound.instance', 'kNotFound', 'db', 404, 'Instance not found.'],
  ['cortex.notFound.missingMediaSource', 'kMissingMediaSource', 'files', 404, 'A file source is missing from the upload.'],
  ['cortex.notFound.missingQueueMessage', 'kMissingQueueMessage', 'queue', 404, 'Message missing.'],
  ['cortex.notFound.missingQueueTaskProcessor', 'kMissingQueueTaskProcessor', 'queue', 404, 'Task processor not found.'],
  ['cortex.notFound.notificationTemplateSpec', 'kNotFound', 'notifications', 404, 'Missing notification worker template spec.'],
  ['cortex.notFound.notificationTemplateVariable', 'kNotFound', 'notifications', 404, 'Missing notification worker template variable.'],
  ['cortex.notFound.object', 'kNotFound', 'db', 404, 'Object not found.'],
  ['cortex.notFound.org', 'kNotFound', 'db', 404, 'Org not found.'],
  ['cortex.notFound.passwordResetToken', 'kNotFound', 'fault', 404, 'Invalid password reset token.'],
  ['cortex.notFound.pathEndedPrematurely', 'kNotFound', 'db', 404, 'Property path ended prematurely.'],
  ['cortex.notFound.primitivePropertySelection', 'kNotFound', 'db', 404, 'Selection not found inside of primitive value.'],
  ['cortex.notFound.principal', 'kNotFound', 'fault', 404, 'Principal not found.'],
  ['cortex.notFound.property', 'kNotFound', 'db', 404, 'Property not found.'],
  ['cortex.notFound.propertyModel', 'kNotFound', 'db', 404, 'Property model not found.'],
  ['cortex.notFound.propertyNode', 'kNotFound', 'db', 404, 'Property node not found.'],
  ['cortex.notFound.propertySelection', 'kNotFound', 'db', 404, 'One or more sub-properties could not be found.'],
  ['cortex.notFound.role', 'kNotFound', 'fault', 404, 'Role not found.'],
  ['cortex.notFound.route', 'kNotFound', 'fault', 404, 'Route not found.'],
  ['cortex.notFound.script', 'kNotFound', 'db', 404, 'Script not found.'],
  ['cortex.notFound.serviceAccount', 'kNotFound', 'fault', 404, 'Service account not found.'],
  ['cortex.notFound.sourceObject', 'kNotFound', 'db', 404, 'The source object could not be discerned. Try to narrow down your search to a single object.'],
  ['cortex.notFound.storage', 'kNotFound', 'db', 404, 'Storage location not found.'],
  ['cortex.notFound.template', 'kNotFound', 'db', 404, 'Template not found.'],
  ['cortex.notFound.unspecified', 'kNotFound', 'db', 404, 'Resource not found.'],
  ['cortex.notFound.view', 'kNotFound', 'db', 404, 'View not found.'],
  ['cortex.notImplemented.indexedArrayUpdates', 'kNotImplemented', 'db', 501, 'Indexed array updates are not yet supported.'],
  ['cortex.notImplemented.pointerUrl', 'kNotImplemented', 'files', 501, 'Streaming from URL not implemented for storage location.'],
  ['cortex.notImplemented.unspecified', 'kNotImplemented', 'error', 501, 'Not implemented.'],
  ['cortex.success.newLocation', 'kNewLocation', 'location', 200, 'A new location has been added to the account. Please verify it.'],
  ['cortex.throttled.policy', 'kThrottled', 'policy', 429, 'Policy throttled request.'],
  ['cortex.throttled.stalledCursor', 'kThrottled', 'api', 429, 'Stalled cursor was closed.'],
  ['cortex.throttled.unspecified', 'kThrottled', 'error', 429, 'Request throttled.'],
  ['cortex.timeout.apnsNotification', 'kTimeout', 'notifcations', 408, 'APNs notification timeout.'],
  ['cortex.timeout.dbQuery', 'kTimeout', 'db', 408, 'The query took too long to complete and was aborted.'],
  ['cortex.timeout.envActivity', 'kTimeout', 'deployment', 408, 'Gave up waiting for environment activity to cease.'],
  ['cortex.timeout.queueMessage', 'kMessageTimeout', 'queue', 408, 'Message timed out.'],
  ['cortex.timeout.smsNotification', 'kSmsTimeout', 'sms', 408, 'SMS Timeout.'],
  ['cortex.timeout.unspecified', 'kTimeout', 'error', 408, 'Timeout.'],
  ['cortex.tooBusy.sandbox', 'kTooBusy', 'api', 429, 'Sandbox too busy.'],
  ['cortex.tooBusy.unspecified', 'kTooBusy', 'error', 429, 'Server too busy.'],
  ['cortex.tooLarge.config', 'kTooLarge', 'db', 413, 'Breached maximum config storage limit.'],
  ['cortex.tooLarge.connectionTargets', 'kTooLarge', 'connections', 413, 'Too many connection targets.'],
  ['cortex.tooLarge.memo', 'kRequestTooLarge', 'api', 413, 'Memo too large.'],
  ['cortex.tooLarge.unspecified', 'kRequestTooLarge', 'api', 413, 'Request too large.'],
  ['cortex.unsupportedMediaType.facetMime', 'kMediaTypeNotAllowed', 'files', 415, 'The file type does not match allowed mime types for facet.'],
  ['cortex.unsupportedOperation.directAclWrite', 'kUnsupportedOperation', 'db', 501, 'Direct acl write.'],
  ['cortex.unsupportedOperation.documentMerge', 'kUnsupportedOperation', 'db', 501, 'Unsupported document merge.'],
  ['cortex.unsupportedOperation.exactMatching', 'kUnsupportedOperation', 'db', 501, 'Exact array/object property matching is unsupported.'],
  ['cortex.unsupportedOperation.patchOp', 'kUnsupportedOperation', 'db', 501, 'Unsupported or missing patch operation (op) property.'],
  ['cortex.unsupportedOperation.requestMethodDoesNotMatchOperationSemantics', 'kUnsupportedOperation', 'db', 501, 'Unsupported request method.'],
  ['cortex.unsupportedOperation.setOwnerRequiresOwner', 'kUnsupportedOperation', 'db', 501, 'setOwner operation cannot set ownership of contexts without an owner.'],
  ['cortex.unsupportedOperation.typedQueryExpression', 'kUnsupportedOperation', 'db', 501, 'Properties in objects with multiple types that share a name cannot be included in some combinations of expressions.'],
  ['cortex.unsupportedOperation.uniqueKeyNotSet', 'kUnsupportedOperation', 'developer', 501, 'The unique key must be set to import/export this instance.'],
  ['cortex.unsupportedOperation.uniqueKeyRequiredForExport', 'kUnsupportedOperation', 'developer', 501, 'A unique key must be defined for the object in order to import/export.'],
  ['cortex.unsupportedOperation.unspecified', 'kUnsupportedOperation', 'error', 501, 'Unsupported Operation'],
  ['cortex.validation.JSONSchemaValidation', 'kInvalidArgument', 'validation', 400, 'JSON schema validation failed'],
  ['script.accessDenied.acl', 'kAccessDenied', 'scripts', 403, 'Insufficient script access.'],
  ['script.accessDenied.command', 'kAccessDenied', 'scripts', 403, 'Cannot call api command.'],
  ['script.error.cancelled', 'kCancelled', 'scripts', 500, 'Script execution was cancelled.'],
  ['script.error.connectionNotReady', 'kError', 'scripts', 500, 'Script sandbox connection failed.'],
  ['script.error.context', 'kError', 'scripts', 500, 'The script context is not available.'],
  ['script.error.didNotComplete', 'kScriptError', 'scripts', 500, 'A script did not complete.'],
  ['script.error.headersWritten', 'kScriptError', 'scripts', 500, 'Headers cannot be set once data has been written.'],
  ['script.error.marshalling', 'kError', 'scripts', 500, 'Script marshalling error. A data object could not be converted for transport. It is possible a value may contain enumerable getters.'],
  ['script.error.memory', 'kOutOfMemory', 'scripts', 500, 'Script out of memory.'],
  ['script.error.ops', 'kScriptError', 'scripts', 500, 'Max script ops exceeded.'],
  ['script.error.sandboxClosed', 'kError', 'scripts', 500, 'Script sandbox connection closed unexpectedly.'],
  ['script.error.stacked', 'kError', 'scripts', 500, 'Script api calls are not stackable. It is possible an api call was made in a nested require.'],
  ['script.error.unspecified', 'kScriptError', 'scripts', 500, 'An unspecified script error occured.'],
  ['script.invalidArgument.acl', 'kInvalidArgument', 'scripts', 400, 'Invalid acl arguments.'],
  ['script.invalidArgument.executionDepthExceeded', 'kInvalidArgument', 'scripts', 400, 'Max script execution depth exceeded.'],
  ['script.invalidArgument.unknownCommand', 'kInvalidArgument', 'scripts', 400, 'Script called an unknown api command.'],
  ['script.notFound.cursor', 'kScriptError', 'scripts', 404, 'Cursor not found.'],
  ['script.timeout.execution', 'kTimeout', 'scripts', 408, 'Script execution timed out.'],
  ['script.timeout.sandboxStartup', 'kTimeout', 'scripts', 408, 'Script sandbox startup timeout.'],
  ['cortex.sms.blockedNumber', 'kBlocked', 'sms', 400, 'Cannot send an SMS message to a blocked number']
].forEach(entry => {
  Fault.addCode(entry[1], entry[2], entry[3], entry[4], entry[0])
})
